services:
  react:
    container_name: react
    image: node:24.13.0
    depends_on:
      - fastapi
    ports:
      - 80:5173
    volumes:
      - ../workspace/frontend:/workspace
    command: ["sleep", "infinity"]
  
  fastapi:
    container_name: fastapi
    image: python:3.13.11
    depends_on:
      - mariadb
    ports:
      - 8000:8000
    volumes:
      - ../workspace/backend:/workspace
    command: ["sleep", "infinity"]
  
  mariadb:
    container_name: mariadb
    image: mariadb:12.1.2
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ../workspace/mariadb/conf.d:/etc/mysql/conf.d:ro
      - ../workspace/mariadb/data:/var/lib/mysql:rw
      - ../workspace/mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3306
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=edu
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8
